name: Biome Code Quality Check

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  biome-check:
    name: Run Biome Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Biome lint
        run: npm run lint
        
      - name: Run Biome format check
        run: npm run format
        
      - name: Run Biome check (comprehensive)
        run: npm run biome:ci
        
      - name: Comment PR on failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Biome checks failed!** Please fix the code quality issues before merging.\n\n💡 Run `npm run check:fix` locally to automatically fix some issues.'
            })
            
  biome-status-check:
    name: Biome Status Check
    runs-on: ubuntu-latest
    needs: biome-check
    if: always()
    
    steps:
      - name: Check if Biome passed
        run: |
          if [ "${{ needs.biome-check.result }}" != "success" ]; then
            echo "Biome checks failed - blocking merge"
            exit 1
          else
            echo "Biome checks passed - ready to merge"
          fi